# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://belak1.github.io/
# baseurl:
title: Brian Belak
author: Brian Belak
description: Personal website and resume
avatar: 16mm-stamp_web.png
email: brianbelak@gmail.com
github: belak1
twitter: brianjbelak
linkedin: brianbelak
# stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
# disqus: username
# google_analytics: 


# needed for travis-ci build
exclude: [vendor]
